# Generated by Django 5.0.1 on 2024-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
