# Generated by Django 5.0.1 on 2024-02-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_student_username_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
    ]
