# Generated by Django 5.0.1 on 2024-02-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0007_rename_user_leave_student_remove_leave_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
